/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Catalog: typeof import('./src/components/Catalog/index.vue')['default']
    Comment: typeof import('./src/components/Comment/Comment.vue')['default']
    CommentChildren: typeof import('./src/components/Comment/CommentChildren.vue')['default']
    CommentForm: typeof import('./src/components/Comment/CommentForm.vue')['default']
    CommentItem: typeof import('./src/components/Comment/CommentItem.vue')['default']
    DaySwitch: typeof import('./src/components/DaySwitch.vue')['default']
    DetailPageHeader: typeof import('./src/components/DetailPageHeader.vue')['default']
    DynamicBackground: typeof import('./src/components/Layout/DynamicBackground.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/Layout/Footer/index.vue')['default']
    Header: typeof import('./src/components/Layout/Header/index.vue')['default']
    IconAccount: typeof import('./src/components/icons/IconAccount.vue')['default']
    IconArticle: typeof import('./src/components/icons/IconArticle.vue')['default']
    IconBilibili: typeof import('./src/components/icons/IconBilibili.vue')['default']
    IconBook: typeof import('./src/components/icons/IconBook.vue')['default']
    IconComment: typeof import('./src/components/icons/IconComment.vue')['default']
    IconCommentPoint: typeof import('./src/components/icons/IconCommentPoint.vue')['default']
    IconEmail: typeof import('./src/components/icons/IconEmail.vue')['default']
    IconEmojiSmile: typeof import('./src/components/icons/IconEmojiSmile.vue')['default']
    IconExit: typeof import('./src/components/icons/IconExit.vue')['default']
    IconEye: typeof import('./src/components/icons/IconEye.vue')['default']
    IconForward: typeof import('./src/components/icons/IconForward.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconLink: typeof import('./src/components/icons/IconLink.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconMoon: typeof import('./src/components/icons/IconMoon.vue')['default']
    IconPaperPlane: typeof import('./src/components/icons/IconPaperPlane.vue')['default']
    IconQQ: typeof import('./src/components/icons/IconQQ.vue')['default']
    IconRight3: typeof import('./src/components/icons/IconRight3.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSun: typeof import('./src/components/icons/IconSun.vue')['default']
    IconTime: typeof import('./src/components/icons/IconTime.vue')['default']
    IconUpdateTIme: typeof import('./src/components/icons/IconUpdateTIme.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    IconYellowEmail: typeof import('./src/components/icons/IconYellowEmail.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    MobileMenuDrawer: typeof import('./src/components/mobile/MobileMenuDrawer.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SideCard: typeof import('./src/components/SideCard.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    WaveEffect: typeof import('./src/components/WaveEffect.vue')['default']
  }
}
